[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "max_assistant_v2"
version = "0.1.0"
description = "FRANK Assistant V2"
authors = [{name = "Bruno"}]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
